name: katherinekerpan
favicon: null
layout_spectrum: 0.8557760098483413
typography_spectrum: 0.7508644857443869
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.6027446060907096
  lightness: 0.03035674965940416
  saturation: 0.7487182191107422
  rhythmicContrast: 0.058426341973245144
purpose: []
